version: '3.5'

networks:
  app-network:
    driver: ${NETWORKS_DRIVER}

services:
  caddy:
    build: ./caddy
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      - ${CADDY_CONFIG_PATH}:/etc/caddy
      - ${CADDY_HOST_LOG_PATH}:/var/log/caddy
      - ${DATA_PATH_HOST}:/root/.caddy
    ports:
      - "${CADDY_HOST_HTTP_PORT}:80"
      - "${CADDY_HOST_HTTPS_PORT}:443"
    depends_on:
      - php-fpm
    networks:
      - app-network

  php-fpm:
    build:
      context: ./php-fpm
    image: php:7.4-fpm
    container_name: app
    restart: unless-stopped
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
    tty: true
    environment:
      SERVICE_NAME: php-fpm
      SERVICE_TAGS: dev
    working_dir: /var/www
    networks:
      - app-network

  mysql:
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${WORKSPACE_TIMEZONE}
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - app-network
